#### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Load Dataset and merge them

In [31]:
features = pd.read_csv(r"C:\Users\User\Desktop\Walmart Sales Forecast\Data\features.csv")
stores = pd.read_csv(r"C:\Users\User\Desktop\Walmart Sales Forecast\Data\stores.csv")
train = pd.read_csv(r"C:\Users\User\Desktop\Walmart Sales Forecast\Data\train.csv")
test = pd.read_csv(r"C:\Users\User\Desktop\Walmart Sales Forecast\Data\test.csv")
print("features shape :", features.shape)
print("stores shape :", stores.shape)
print("train shape :", train.shape)
print("test shape :", test.shape, "\n")

merged_data = train.merge(features, how="left", on=["Store", "Date", "IsHoliday"])
merged_data = merged_data.merge(stores, how="left", on=["Store"])

merged_data.drop(columns=["MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5"], inplace=True)
print(merged_data.info())

print("\nData shape: ", merged_data.shape)

features shape : (8190, 12)
stores shape : (45, 3)
train shape : (421570, 5)
test shape : (115064, 4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  object
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
 5   Temperature   421570 non-null  float64
 6   Fuel_Price    421570 non-null  float64
 7   CPI           421570 non-null  float64
 8   Unemployment  421570 non-null  float64
 9   Type          421570 non-null  object
 10  Size          421570 non-null  int64
dtypes: bool(1), float64(5), int64(3), object(2)
memory usage: 32.6+ MB
None

Data shape:  (421570, 11)

In [32]:
merged_data.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,CPI,Unemployment,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,211.096358,8.106,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,211.242170,8.106,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,211.289143,8.106,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,211.319643,8.106,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,211.350143,8.106,A,151315

#### Data Preprocessing

##### Feature Encoding

In [40]:
from sklearn.preprocessing import OneHotEncoder

data = merged_data[merged_data["Weekly_Sales"]>0]

onehotencoder = OneHotEncoder(sparse_output=False)
encoded_type = onehotencoder.fit_transform(data[["Type"]])
encoded_df = pd.DataFrame(encoded_type, columns=onehotencoder.get_feature_names_out(["Type"]))

data = pd.concat([data, encoded_df], axis=1)
data.drop(columns=["Type"], inplace=True)

data["IsHoliday"] = data["IsHoliday"].map({False: 0, True: 1})

data["Date"] = pd.to_datetime(data["Date"])
data["Year"] = data["Date"].dt.year
data["Week"] = data["Date"].dt.isocalendar().week
data.drop(columns=["Date"], inplace=True)

print("Data Shape: ", data.shape)
data.head()

Data Shape:  (421570, 14)

,Store,Dept,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,CPI,Unemployment,Size,Type_A,Type_B,Type_C,Year,Week
0,1.0,1.0,24924.50,0.0,42.31,2.572,211.096358,8.106,151315.0,1.0,0.0,0.0,2010.0,5
1,1.0,1.0,46039.49,1.0,38.51,2.548,211.242170,8.106,151315.0,1.0,0.0,0.0,2010.0,6
2,1.0,1.0,41595.55,0.0,39.93,2.514,211.289143,8.106,151315.0,1.0,0.0,0.0,2010.0,7
3,1.0,1.0,19403.54,0.0,46.63,2.561,211.319643,8.106,151315.0,1.0,0.0,0.0,2010.0,8
4,1.0,1.0,21827.90,0.0,46.50,2.625,211.350143,8.106,151315.0,1.0,0.0,0.0,2010.0,9

##### Train-Test Split

In [1]:
from sklearn.model_selection import train_test_split

features = data.drop(columns=["Weekly_Sales"], inplace=False)
target = data[["Weekly_Sales"]]

x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=42)

print("x_train shape: ", x_train.shape)
print("x_test shape: ", x_test.shape)
print("y_train shape: ", y_train.shape)
print("y_test shape: ", y_test.shape)

NameError: name 'data' is not defined